version: "3.8"
services:
 db:
   container_name: pg_container
   image: postgres
   restart: always
   environment:
     POSTGRES_USER: YOUR_USER_NAME
     POSTGRES_PASSWORD: YOUR_USER_PASSWORD
     POSTGRES_DB: YOUR_DB_NAME
   ports:
     - "5432:5432"
   volumes:
     - pg_data:/var/lib/postgresql/data/

  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      - VIRTUAL_HOST=92.255.77.155
  #  depends_on:
  #    - db


#volumes:
#  pg_data:
